### ISSUE TITLE
Provide a way to disable a source without removing it from the mosaic config file

### ISSUE THREAD

**Issue by DavieReid** [jpmorganchase/mosaic#255]
There are a few instances when you may want to flag a source as disabled, to prevent mosaic from loading docs from that source.  You *can* do this with a namespace but it's a little unintuitive and may have routing implications.

1. local development where the developer wishes to prefer the local source over a remote source e.g. github
2. internal sources vs external sources.

**Comment by mark-tate** [comment]
Just ran into this myself and was about to raise the same issue.

Ideally we do this via the `core` code, so we do not need to modify every source.
SourceWorker or something.

The use-case for this, is the ability to switch between local and remote docs and share the same namespace.

ie. When running locally, I want `salt` namespace to point at local docs and remote docs disabled.
When not running remotely, I want the remote sources enabled using the `salt` namespace and local source disabled.

We should then modify the standard generator config, so the disable flag on the Source plugin is driven by the current environment. We had something similar in Strapi/Mosaic v1, with the environment driven vars.

At present I need to edit the mosaic.config and comment out sources to avoid them overwriting  sharing the same namespace.
