### ISSUE TITLE
Improve font loading

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/mosaic#316]
Currently, font loading is working via a custom Document with `link` elements being injected into the head https://github.com/jpmorganchase/mosaic/blob/main/packages/site-components/src/Document.tsx

This affects the initial paint time and slows down the site loading. Ideally, Mosaic should rely on next/font here, e.g. https://github.com/jpmorganchase/salt-ds/pull/1509

**Comment by DavieReid** [comment]
https://github.com/jpmorganchase/mosaic/pull/358
